### ISSUE TITLE
Announcements

### ISSUE THREAD

**Issue by EdricChan03** [EdricChan03/ngx-ytd-api#50]
This issue contains announcements about this project.

(Note that times are in timezone GMT+8 unless otherwise stated)

# List of announcements

* [**19 December 2018** - Project is blocked on minor issue](https://github.com/Chan4077/ngx-ytd-api/issues/50#issuecomment-448633408)
* [**20 December 2018** - Issue is regressing](https://github.com/Chan4077/ngx-ytd-api/issues/50#issuecomment-448932737)
* [**21 December 2018** - Issue has been fixed](https://github.com/Chan4077/ngx-ytd-api/issues/50#issuecomment-449228789)
* [**22 December 2018** - All other issues fixed; new release when?](https://github.com/Chan4077/ngx-ytd-api/issues/50#issuecomment-449578020)
* [**24 December 2018** - New release by end of December](https://github.com/Chan4077/ngx-ytd-api/issues/50#issuecomment-449718009)
* [**1 January 2019** - New release!](https://github.com/Chan4077/ngx-ytd-api/issues/50#issuecomment-450709600)
* [**16 February 2019** - Temporary removal of schematics](https://github.com/Chan4077/ngx-ytd-api/issues/50#issuecomment-464309791)

**Comment by Chan4077** [comment]
# 20 December 2018

I'm currently working on trying to fix the minor issue.

However, it seems that I may have reached a dead end.

Here's the error log if anyone's interested:

```
BUILD ERROR
projects/ngx-ytd-api-lib/src/lib/public_api.ts(7,15): error TS2307: Cannot find module 'ngx-ytd-api/comments'.
projects/ngx-ytd-api-lib/src/lib/public_api.ts(8,15): error TS2307: Cannot find module 'ngx-ytd-api/core'.
projects/ngx-ytd-api-lib/src/lib/public_api.ts(9,15): error TS2307: Cannot find module 'ngx-ytd-api/search'.
projects/ngx-ytd-api-lib/src/lib/public_api.ts(10,15): error TS2307: Cannot find module 'ngx-ytd-api/videos'.

Error: projects/ngx-ytd-api-lib/src/lib/public_api.ts(7,15): error TS2307: Cannot find module 'ngx-ytd-api/comments'.
projects/ngx-ytd-api-lib/src/lib/public_api.ts(8,15): error TS2307: Cannot find module 'ngx-ytd-api/core'.
projects/ngx-ytd-api-lib/src/lib/public_api.ts(9,15): error TS2307: Cannot find module 'ngx-ytd-api/search'.
projects/ngx-ytd-api-lib/src/lib/public_api.ts(10,15): error TS2307: Cannot find module 'ngx-ytd-api/videos'.

    at Object.<anonymous> (/Users/edricchan/Desktop/Projects/angular/ngx-ytd-api/node_modules/ng-packagr/lib/ngc/compile-source-files.js:40:68)
    at Generator.next (<anonymous>)
    at /Users/edricchan/Desktop/Projects/angular/ngx-ytd-api/node_modules/ng-packagr/lib/ngc/compile-source-files.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/edricchan/Desktop/Projects/angular/ngx-ytd-api/node_modules/ng-packagr/lib/ngc/compile-source-files.js:3:12)
    at Object.compileSourceFiles (/Users/edricchan/Desktop/Projects/angular/ngx-ytd-api/node_modules/ng-packagr/lib/ngc/compile-source-files.js:17:12)
    at Object.<anonymous> (/Users/edricchan/Desktop/Projects/angular/ngx-ytd-api/node_modules/ng-packagr/lib/ng-v5/entry-point/ts/compile-ngc.transform.js:31:32)
    at Generator.next (<anonymous>)
    at /Users/edricchan/Desktop/Projects/angular/ngx-ytd-api/node_modules/ng-packagr/lib/ng-v5/entry-point/ts/compile-ngc.transform.js:7:71
    at new Promise (<anonymous>)
```

This occurs when compiling the library with `ng build ngx-ytd-api-lib --watch`.

**Comment by Chan4077** [comment]
# 24 December 2018 (18:45)

Expect a new release by the end of December!

**Comment by Chan4077** [comment]
# 1 January 2019 (12:43)

`1.0.0-alpha.4` has been released!

Check out the [changelog](https://github.com/Chan4077/ngx-ytd-api/blob/master/CHANGELOG.md#1.0.0-alpha.4) for what's new in `1.0.0-alpha.4`.

**Comment by Chan4077** [comment]
# 16 February 2019 (16:02)

Support for schematics has been temporarily removed.

**Comment by EdricChan03** [comment]
# 12 January 2020

The library has been deprecated in favour of the [JavaScript `gapi` library](https://github.com/google/google-api-javascript-client).
